# Site settings
title: CloudCannon Blog Demo
email: team@variantstudios.com
description:
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://kind-rose.cloudvent.net/ # the base hostname & protocol for your site
timezone: America/Denver

version: 2.4.0

# Site Author(s)
author:
  name: Variant Studios
  email: team@variantstudios.com

# Build settings
highlighter: pygments
markdown: kramdown
kramdown:
  auto_ids: true
  toc_levels: 1..6

# Permalinks

# Include Sub Pages
# include: ['_pages']

# Blog Settings
paginate: 10
paginate_path: "/page:num/"

# Collections
collections:

defaults:
  - scope:
      type: "news"
    values:
      layout: "post"

# Reading Time Feature
reading_time:     true
words_per_minute: 200

# Disqus Comments
disqus_short_name:
disqus_show_comment_count:

# typekit
typekit: 

# Social Media
facebook: ""
twitter: ""

# Google Analytics
google_analytics_tracking_id: ""

# exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]